# Generated by Django 4.2.4 on 2023-09-05 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Funda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('peso_funda', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('cuenta_lbs', models.PositiveIntegerField()),
                ('total_camaron', models.PositiveIntegerField()),
                ('uniformidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_glaseo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca_funda', models.CharField(max_length=50)),
                ('peso_funda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_sin_funda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporte_diario.funda')),
            ],
        ),
        migrations.CreateModel(
            name='PorcentajeDefecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('defecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte_diario.defecto')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte_diario.reportediario')),
            ],
        ),
    ]
