# Generated by Django 4.2.4 on 2023-09-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_diario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportediario',
            name='camarones_grandes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='camarones_pequenos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
