# Generated by Django 4.2.4 on 2023-10-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_diario', '0002_reportediario_camarones_grandes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportediario',
            old_name='marca_funda',
            new_name='marca_funda_manual',
        ),
        migrations.RenameField(
            model_name='reportediario',
            old_name='peso_funda',
            new_name='peso_sin_funda_manual',
        ),
        migrations.RemoveField(
            model_name='reportediario',
            name='funda',
        ),
        migrations.RemoveField(
            model_name='reportediario',
            name='peso_neto',
        ),
        migrations.RemoveField(
            model_name='reportediario',
            name='peso_sin_funda',
        ),
    ]
