# Generated by Django 4.2.4 on 2023-10-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_diario', '0003_rename_marca_funda_reportediario_marca_funda_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportediario',
            name='peso_neto',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
