# Generated by Django 4.2.4 on 2023-10-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_diario', '0004_reportediario_peso_neto'),
    ]

    operations = [
        migrations.AddField(
            model_name='porcentajedefecto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='reportediario',
            name='peso_neto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
