# Generated by Django 4.2.6 on 2023-10-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_diario', '0005_porcentajedefecto_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportediario',
            name='nombre_analista',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='presentacion',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='reportediario',
            name='turno',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
