# Generated by Django 4.2.6 on 2023-10-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_diario', '0007_reportediario_clasificacion_reportediario_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportediario',
            name='total_camaron',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
