# Generated by Django 4.2.6 on 2023-10-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_diario', '0008_alter_reportediario_total_camaron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportediario',
            name='uniformidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
