# Generated by Django 4.2.6 on 2023-10-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_diario', '0009_alter_reportediario_uniformidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportediario',
            name='camarones_grandes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reportediario',
            name='camarones_pequenos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reportediario',
            name='porcentaje_glaseo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
